### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by smiller171** [tinypressco/tinypressco.github.io#18]
the SSL cert on tinypress.co has expired

**Comment by davidbrouillette** [comment]
I know it's obvious, but I see the same. I can't use the service at tinypress.co any longer because of this. Preview has been rendered unusable in Chrome for me.

**Comment by smiller171** [comment]
@davidbrouillette I think the project may be dead. Time for someone to fork it and take up the mantle. There hasn't been any activity on this repo for months.

**Comment by dainmiller** [comment]
Hey @smiller171 and @davidbrouillette,

Sorry for how long it took to update that cert. A bunch of stuff had to be worked out including emails, and where the cert was sent etc etc, ended up taking multiple days to get everything squared away.

A few notes:

1. This project will be open source entirely, very soon. So you all can work on it if you like. But right now, this isn't the repo where the app lives. This is simply the repo for the tinypress blog that is hosted on tinypress via github. So naturally not much changes on this repo.

2. The markdown preview has also been fixed. 

Thanks for reporting.

**Comment by smiller171** [comment]
@dainmiller there are a bunch of open issues here that should probably be moved to the correct repo then.

**Comment by davidbrouillette** [comment]
@dainmiller Thanks for the update. The open issues were placed here since there isn't anywhere else at the moment. I'd be happy to contribute and help maintain the repo once you open source it.
